# Dependencies
markdown:            kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
#
# https://github.com/poole/lanyon/issues/124
permalink:           pretty
relative_permalinks: false

# Setup
title:               Don McCurdy
tagline:             'Software Developer in Cambridge, MA.'
description:         'Personal projects and writing on the web, software development, design, and social impact.'
url:                 https://www.donmccurdy.com
baseurl:             /
paginate:            3
paginate_path:      'page:num'

# About/contact
author:
  name:              Don McCurdy
  twitter_alias:     '@donrmccurdy'
  twitter_url:       https://twitter.com/donrmccurdy
  github_alias:      '@donmccurdy'
  github_url:        https://github.com/donmccurdy
  email:             dm@donmccurdy.com

# Formatting
redcarpet:
  extensions:        ['smart', 'strikethrough', 'tables']

# Dependencies
gems:
- jekyll-paginate

# Custom vars
version:             1.0.0
